language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/BreadMoirai/travis_discord/master/travis.sh)"
after_failure:
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/BreadMoirai/travis_discord/master/travis.sh)"